/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pck_practica6;

/**
 *
 * @author Airam
 * @author Gioele
 * 
 */
public class ColorStatisticsPanel extends javax.swing.JPanel {

    private static final int RED = 2;
    private static final int GREEN = 1;
    private static final int BLUE = 0;
    private static final String BLANK = " ";

    public ColorStatisticsPanel() {
        initComponents();
        initStatisticsText();
    }

    private void initStatisticsText() {
        maxRedText.setText(BLANK);
        minRedText.setText(BLANK);
        avgRedText.setText(BLANK);
        maxGreenText.setText(BLANK);
        minGreenText.setText(BLANK);
        avgGreenText.setText(BLANK);
        maxBlueText.setText(BLANK);
        minBlueText.setText(BLANK);
        avgBlueText.setText(BLANK);
    }

    public void setStatistics(int[] max, int[] min, int[] avg) {
        maxRedText.setText(String.valueOf(max[RED]));
        minRedText.setText(String.valueOf(min[RED]));
        avgRedText.setText(String.valueOf(avg[RED]));
        maxGreenText.setText(String.valueOf(max[GREEN]));
        minGreenText.setText(String.valueOf(min[GREEN]));
        avgGreenText.setText(String.valueOf(avg[GREEN]));
        maxBlueText.setText(String.valueOf(max[BLUE]));
        minBlueText.setText(String.valueOf(min[BLUE]));
        avgBlueText.setText(String.valueOf(avg[BLUE]));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        redStatisticsPanel = new javax.swing.JPanel();
        maxRedLabel = new javax.swing.JLabel();
        minRedLabel = new javax.swing.JLabel();
        avgRedLabel = new javax.swing.JLabel();
        maxRedText = new javax.swing.JLabel();
        minRedText = new javax.swing.JLabel();
        avgRedText = new javax.swing.JLabel();
        greenStatisticsPanel = new javax.swing.JPanel();
        maxGreenLabel = new javax.swing.JLabel();
        minGreenLabel = new javax.swing.JLabel();
        avgGreenLabel = new javax.swing.JLabel();
        maxGreenText = new javax.swing.JLabel();
        minGreenText = new javax.swing.JLabel();
        avgGreenText = new javax.swing.JLabel();
        blueStatisticsPanel = new javax.swing.JPanel();
        maxBlueLabel = new javax.swing.JLabel();
        minBlueLabel = new javax.swing.JLabel();
        avgBlueLabel = new javax.swing.JLabel();
        maxBlueText = new javax.swing.JLabel();
        minBlueText = new javax.swing.JLabel();
        avgBlueText = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder("Estadísticas de color"));

        redStatisticsPanel.setBackground(new java.awt.Color(255, 255, 255));
        redStatisticsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Rojo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 0, 0))); // NOI18N

        maxRedLabel.setText("Máximo:");

        minRedLabel.setText("Mínimo:");

        avgRedLabel.setText("Promedio:");

        maxRedText.setText("   ");
        maxRedText.setToolTipText("Máximo del componente rojo");

        minRedText.setText("   ");
        minRedText.setToolTipText("Mínimo del componente rojo");

        avgRedText.setText("   ");
        avgRedText.setToolTipText("Promedio del componente rojo");

        javax.swing.GroupLayout redStatisticsPanelLayout = new javax.swing.GroupLayout(redStatisticsPanel);
        redStatisticsPanel.setLayout(redStatisticsPanelLayout);
        redStatisticsPanelLayout.setHorizontalGroup(
            redStatisticsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(redStatisticsPanelLayout.createSequentialGroup()
                .addGroup(redStatisticsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(avgRedLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(maxRedLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(minRedLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(redStatisticsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(avgRedText, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(minRedText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(maxRedText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        redStatisticsPanelLayout.setVerticalGroup(
            redStatisticsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(redStatisticsPanelLayout.createSequentialGroup()
                .addGroup(redStatisticsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maxRedLabel)
                    .addComponent(maxRedText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(redStatisticsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minRedLabel)
                    .addComponent(minRedText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(redStatisticsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(avgRedLabel)
                    .addComponent(avgRedText)))
        );

        greenStatisticsPanel.setBackground(new java.awt.Color(255, 255, 255));
        greenStatisticsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Verde", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 255, 0))); // NOI18N

        maxGreenLabel.setText("Máximo:");

        minGreenLabel.setText("Mínimo:");

        avgGreenLabel.setText("Promedio:");

        maxGreenText.setText("   ");
        maxGreenText.setToolTipText("Máximo del componente verde");

        minGreenText.setText("   ");
        minGreenText.setToolTipText("Mínimo del componente verde");

        avgGreenText.setText("   ");
        avgGreenText.setToolTipText("Promedio del componente verde");

        javax.swing.GroupLayout greenStatisticsPanelLayout = new javax.swing.GroupLayout(greenStatisticsPanel);
        greenStatisticsPanel.setLayout(greenStatisticsPanelLayout);
        greenStatisticsPanelLayout.setHorizontalGroup(
            greenStatisticsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(greenStatisticsPanelLayout.createSequentialGroup()
                .addGroup(greenStatisticsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(avgGreenLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(minGreenLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(maxGreenLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(greenStatisticsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(avgGreenText, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(minGreenText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(maxGreenText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        greenStatisticsPanelLayout.setVerticalGroup(
            greenStatisticsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(greenStatisticsPanelLayout.createSequentialGroup()
                .addGroup(greenStatisticsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maxGreenLabel)
                    .addComponent(maxGreenText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(greenStatisticsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minGreenLabel)
                    .addComponent(minGreenText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(greenStatisticsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(avgGreenLabel)
                    .addComponent(avgGreenText)))
        );

        blueStatisticsPanel.setBackground(new java.awt.Color(255, 255, 255));
        blueStatisticsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Azul", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 255))); // NOI18N

        maxBlueLabel.setText("Máximo:");

        minBlueLabel.setText("Mínimo:");

        avgBlueLabel.setText("Promedio:");

        maxBlueText.setText("   ");
        maxBlueText.setToolTipText("Máximo del componente azul");

        minBlueText.setText("   ");
        minBlueText.setToolTipText("Mínimo del componente azul");

        avgBlueText.setText("   ");
        avgBlueText.setToolTipText("Promedio del componente azul");

        javax.swing.GroupLayout blueStatisticsPanelLayout = new javax.swing.GroupLayout(blueStatisticsPanel);
        blueStatisticsPanel.setLayout(blueStatisticsPanelLayout);
        blueStatisticsPanelLayout.setHorizontalGroup(
            blueStatisticsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(blueStatisticsPanelLayout.createSequentialGroup()
                .addGroup(blueStatisticsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(avgBlueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(maxBlueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(minBlueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(blueStatisticsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(avgBlueText, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(minBlueText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(maxBlueText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        blueStatisticsPanelLayout.setVerticalGroup(
            blueStatisticsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(blueStatisticsPanelLayout.createSequentialGroup()
                .addGroup(blueStatisticsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maxBlueLabel)
                    .addComponent(maxBlueText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(blueStatisticsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minBlueLabel)
                    .addComponent(minBlueText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(blueStatisticsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(avgBlueLabel)
                    .addComponent(avgBlueText)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(redStatisticsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(greenStatisticsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(blueStatisticsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(greenStatisticsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(redStatisticsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(blueStatisticsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>                        


    // Variables declaration - do not modify                     
    private javax.swing.JLabel avgBlueLabel;
    private javax.swing.JLabel avgBlueText;
    private javax.swing.JLabel avgGreenLabel;
    private javax.swing.JLabel avgGreenText;
    private javax.swing.JLabel avgRedLabel;
    private javax.swing.JLabel avgRedText;
    private javax.swing.JPanel blueStatisticsPanel;
    private javax.swing.JPanel greenStatisticsPanel;
    private javax.swing.JLabel maxBlueLabel;
    private javax.swing.JLabel maxBlueText;
    private javax.swing.JLabel maxGreenLabel;
    private javax.swing.JLabel maxGreenText;
    private javax.swing.JLabel maxRedLabel;
    private javax.swing.JLabel maxRedText;
    private javax.swing.JLabel minBlueLabel;
    private javax.swing.JLabel minBlueText;
    private javax.swing.JLabel minGreenLabel;
    private javax.swing.JLabel minGreenText;
    private javax.swing.JLabel minRedLabel;
    private javax.swing.JLabel minRedText;
    private javax.swing.JPanel redStatisticsPanel;
    // End of variables declaration                   
}
